title: <p align="center"> Arijeet Saha </p>
logo: /assets/img/Arijeet_Saha.jpg

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/arijeet-saha-8500a944/">LinkedIn</a> |
  <a href="https://github.com/arijeetsaha">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  I also work an a Software architect for Backend applications
  <br>
  </p>


remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
